M48
; DRILL file {KiCad 7.0.9} date Thursday, September 19, 2024 at 10:53:50 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-19T22:53:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.0748Y-1.8717
X4.0748Y-3.7992
X7.1063Y-1.8717
X7.1063Y-3.7992
T0
M30
